import js from "@eslint/js";
import globals from "globals";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // next-env.d.ts is generated by Next on every build and uses a triple-slash
  // reference the TS rules reject. It is not ours to fix and regenerates anyway.
  { ignores: [".next", "node_modules", "e2e/.artifacts", "playwright-report", "next-env.d.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2022,
      globals: { ...globals.browser, ...globals.node },
    },
  },
);
